from __future__ import annotations

from io import BytesIO
from pathlib import Path
from typing import Any

import pandas as pd
from openpyxl import Workbook
from openpyxl.chart import BarChart, LineChart, PieChart, Reference
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils.dataframe import dataframe_to_rows


def read_tabular(content: bytes, filename: str, sheet_name: str | int | None = 0) -> tuple[pd.DataFrame, list[str], str | None]:
    name = filename.lower()
    if name.endswith(".csv") or name.endswith(".txt"):
        df = pd.read_csv(BytesIO(content))
        return df, [], None
    if name.endswith((".xlsx", ".xls", ".xlsm")):
        xl = pd.ExcelFile(BytesIO(content))
        sheets = list(xl.sheet_names)
        chosen = sheets[0] if sheet_name is None else (
            sheets[sheet_name] if isinstance(sheet_name, int) else sheet_name
        )
        if chosen not in sheets:
            chosen = sheets[0]
        df = pd.read_excel(xl, sheet_name=chosen)
        return df, sheets, chosen
    raise ValueError("Unsupported file type. Upload .xlsx, .xls, .xlsm, or .csv")


def _style_header(ws, row: int = 1) -> None:
    fill = PatternFill("solid", fgColor="1F4E79")
    font = Font(color="FFFFFF", bold=True)
    for cell in ws[row]:
        cell.fill = fill
        cell.font = font
        cell.alignment = Alignment(horizontal="center")


def write_analysis_workbook(
    path: Path,
    *,
    data: pd.DataFrame,
    cleaned: pd.DataFrame | None = None,
    tables: dict[str, pd.DataFrame] | None = None,
    insights: list[str] | None = None,
    title: str = "EXCEL-lent Analysis",
) -> Path:
    wb = Workbook()

    # Data sheet
    ws = wb.active
    ws.title = "Data"
    for r in dataframe_to_rows(data, index=False, header=True):
        ws.append(r)
    _style_header(ws)

    if cleaned is not None and not cleaned.equals(data):
        ws_c = wb.create_sheet("Cleaned")
        for r in dataframe_to_rows(cleaned, index=False, header=True):
            ws_c.append(r)
        _style_header(ws_c)

    if tables:
        for name, tdf in tables.items():
            safe = name[:31] or "Table"
            ws_t = wb.create_sheet(safe)
            for r in dataframe_to_rows(tdf, index=False, header=True):
                ws_t.append(r)
            _style_header(ws_t)
            # Add simple bar chart when 2+ columns and enough rows
            if len(tdf.columns) >= 2 and len(tdf) > 0 and len(tdf) <= 30:
                try:
                    chart = BarChart()
                    chart.title = safe
                    chart.y_axis.title = str(tdf.columns[-1])
                    chart.x_axis.title = str(tdf.columns[0])
                    data_ref = Reference(ws_t, min_col=2, min_row=1, max_col=min(3, len(tdf.columns)), max_row=len(tdf) + 1)
                    cats = Reference(ws_t, min_col=1, min_row=2, max_row=len(tdf) + 1)
                    chart.add_data(data_ref, titles_from_data=True)
                    chart.set_categories(cats)
                    chart.shape = 4
                    ws_t.add_chart(chart, "E2")
                except Exception:
                    pass

    if insights:
        ws_i = wb.create_sheet("Insights")
        ws_i["A1"] = title
        ws_i["A1"].font = Font(bold=True, size=14, color="1F4E79")
        ws_i["A2"] = "Generated by EXCEL-lent — Your data analyst, built into Excel."
        ws_i["A4"] = "Key Insights & Alerts"
        ws_i["A4"].font = Font(bold=True)
        for i, line in enumerate(insights, start=5):
            ws_i[f"A{i}"] = line
        ws_i.column_dimensions["A"].width = 100

    # Home / README sheet first conceptually — keep last so Data is primary
    ws_home = wb.create_sheet("About", 0)
    ws_home["A1"] = "EXCEL-lent Data Analyst Engine"
    ws_home["A1"].font = Font(bold=True, size=16, color="1F4E79")
    ws_home["A2"] = "Upload. Ask. Analyze."
    ws_home["A4"] = "This workbook was generated automatically."
    ws_home["A5"] = "Sheets may include: Data, Cleaned, analysis tables, and Insights."
    ws_home.column_dimensions["A"].width = 80

    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)
    return path


def table_to_records(df: pd.DataFrame, limit: int | None = 500) -> list[dict[str, Any]]:
    out = df.copy()
    if limit is not None:
        out = out.head(limit)
    # JSON-safe
    out = out.where(pd.notnull(out), None)
    records = out.to_dict(orient="records")
    for row in records:
        for k, v in list(row.items()):
            if hasattr(v, "item"):
                try:
                    row[k] = v.item()
                except Exception:
                    row[k] = str(v)
            elif isinstance(v, (pd.Timestamp,)):
                row[k] = v.isoformat()
    return records
